# fly.toml app configuration file generated for notification-service-ts on 2025-08-04T16:35:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notification-service-ts'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 9292
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-8x'
