# fly.toml app configuration file generated for order-service-ts on 2025-08-03T23:13:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'order-service-ts'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-16x'
